before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X 'github.com/antham/chyle/cmd.version={{.Version}}'
