language: go

go:
  - 1.8

before_install:
  - export PATH=$PATH:/tmp/
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get github.com/Masterminds/glide
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - mv $GOPATH/bin/gometalinter.v1 $GOPATH/bin/gometalinter
  - gometalinter --install --update

install: glide install

script: make test-all

after_success:
  - bash <(curl -s https://codecov.io/bash)
