language: go

go:
  - 1.8

before_install:
  - export BIN_PATH=$HOME/bin
  - mkdir -p $BIN_PATH
  - export PATH=$BIN_PATH:$PATH
  - wget -O $BIN_PATH/doc-hunt https://github.com/antham/doc-hunt/releases/download/v2.1.1/doc-hunt_linux_amd64
  - chmod 777 $BIN_PATH/doc-hunt
  - wget -O $BIN_PATH/gommit https://github.com/antham/gommit/releases/download/v2.0.0/gommit_linux_386
  - chmod 777 $BIN_PATH/gommit
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - mv $GOPATH/bin/gometalinter.v1 $GOPATH/bin/gometalinter
  - gometalinter --install --update

install: dep ensure -v

script: make test-all

after_success:
  - bash <(curl -s https://codecov.io/bash)
