version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/antham/chyle
    environment:
       BASH_ENV: /home/circleci/.bashrc
    steps:
      - checkout
      - run:
          name: Get doc-hunt binary
          command: |
            mkdir /home/circleci/bin
            wget -O ~/bin/doc-hunt https://github.com/antham/doc-hunt/releases/download/v2.1.1/doc-hunt_linux_amd64 && chmod 777 ~/bin/doc-hunt
      - run:
          name: Get gommit binary
          command: |
            wget -O ~/bin/gommit https://github.com/antham/gommit/releases/download/v2.1.0/gommit_linux_386 && chmod 777 ~/bin/gommit
      - run:
          name: Install dep and gometalinter
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get github.com/alecthomas/gometalinter
            gometalinter --install --update
      - run:
          name: Install vendors
          command: |
            dep ensure -v
      - run:
          name: Run tests
          command: |
            make test-all
      - run:
          name: Run gommit
          command: |
            if [ $CIRCLE_BRANCH != 'master' ]; then ~/bin/gommit check range $(git rev-parse origin/master) $(git rev-parse ${CIRCLE_BRANCH}) ; fi
      - run:
          name: Run doc-hunt
          command: |
            ~/bin/doc-hunt check -e
      - run:
          name: Push on codecov result
          command: |
            bash <(curl -s https://codecov.io/bash)
