version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/antham/chyle
    environment:
       BASH_ENV: /home/circleci/.bashrc
    steps:
      - checkout
      - run:
          name: Get doc-hunt binary
          command: |
            mkdir /home/circleci/bin
            wget -O ~/bin/doc-hunt https://github.com/antham/doc-hunt/releases/download/v2.1.1/doc-hunt_linux_amd64 && chmod 777 ~/bin/doc-hunt
      - run:
          name: Get gommit binary
          command: |
            wget -O ~/bin/gommit https://github.com/antham/gommit/releases/download/v2.1.1/gommit_linux_386 && chmod 777 ~/bin/gommit
      - run:
          name: Install dep and gometalinter
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get github.com/alecthomas/gometalinter
            gometalinter --install --update
      - run:
          name: Install vendors
          command: |
            dep ensure -v
      - run:
          name: Run gometalinter
          command: |
            make gometalinter
      - run:
          name: Run tests
          command: |
            make run-tests
      - run:
          name: Run gommit
          command: |
            if [ $CIRCLE_BRANCH != 'master' ]; then
            git fetch --all
            ~/bin/gommit check range $(git rev-parse origin/master) $(git rev-parse ${CIRCLE_BRANCH})
            fi
      - run:
          name: Run doc-hunt
          command: |
            ~/bin/doc-hunt check -e
      - run:
          name: Push on codecov result
          command: |
            bash <(curl -s https://codecov.io/bash)

  publish:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/antham/chyle
    steps:
      - checkout
      - run:
          name: Fetch tags
          command: |
            git fetch --tags
      - run:
          name: Install dependencies
          command: |
            mkdir /home/circleci/bin
            go get -u github.com/mitchellh/gox
            go get -u github.com/tcnksm/ghr
            go get -u github.com/golang/dep/cmd/dep
            wget -O ~/bin/chyle https://github.com/antham/chyle/releases/download/v1.2.0/chyle_linux_amd64
            chmod 777 ~/bin/chyle
      - run:
          name: Install vendors
          command: |
            dep ensure -v
      - run:
          name: Compile
          command: |
            gox -output "build/{{.Dir}}_{{.OS}}_{{.Arch}}"
      - run:
          run: Upload assets
          command: |
            ghr -u antham $(git tag -l --sort=-v:refname|head -n 1) build/
      - run:
          name: Run chyle
          command: |
            FROM_TAG=$(git tag -l --sort=-v:refname|head -n 2|tail -n 1)
            TO_TAG=$(git tag -l --sort=-v:refname|head -n 1)
            export CHYLE_GIT_REPOSITORY_PATH="."
            export CHYLE_GIT_REFERENCE_FROM="$(git rev-parse $FROM_TAG)"
            export CHYLE_GIT_REFERENCE_TO="$(git rev-parse $TO_TAG)"
            export CHYLE_MATCHERS_TYPE="merge"
            export CHYLE_EXTRACTORS_GITHUBISSUEID_ORIGKEY="message"
            export CHYLE_EXTRACTORS_GITHUBISSUEID_DESTKEY="githubIssueId"
            export CHYLE_EXTRACTORS_GITHUBISSUEID_REG="#(\\d+)"
            export CHYLE_DECORATORS_GITHUBISSUE_CREDENTIALS_OWNER="antham"
            export CHYLE_DECORATORS_GITHUBISSUE_CREDENTIALS_OAUTHTOKEN="$GITHUB_TOKEN"
            export CHYLE_DECORATORS_GITHUBISSUE_KEYS_TITLE_DESTKEY="issueTitle"
            export CHYLE_DECORATORS_GITHUBISSUE_KEYS_TITLE_FIELD="title"
            export CHYLE_DECORATORS_GITHUBISSUE_REPOSITORY_NAME="$CIRCLE_PROJECT_REPONAME"

            export CHYLE_SENDERS_GITHUBRELEASE_CREDENTIALS_OAUTHTOKEN="$GITHUB_TOKEN"
            export CHYLE_SENDERS_GITHUBRELEASE_CREDENTIALS_OWNER="antham"
            export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_TAGNAME="$TO_TAG"
            export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_UPDATE="true"
            export CHYLE_SENDERS_GITHUBRELEASE_REPOSITORY_NAME="$CIRCLE_PROJECT_REPONAME"
            export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_TEMPLATE='### Changes
            {{ range $key, $value := .Datas }}
            => {{ $value.issueTitle }} (#{{ $value.githubIssueId }}) {{ end }}'

            ~/bin/chyle create
workflows:
  version: 2
  build:
    jobs:
      - build
  publish:
    jobs:
      - publish:
          context: org-global
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
